"""Add artist index to Song

Revision ID: 0ec3206ee2f8
Revises: 72ef8599eca9
Create Date: 2020-06-29 19:39:07.182770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec3206ee2f8'
down_revision = '72ef8599eca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_songs_artist_id'), 'songs', ['artist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_artist_id'), table_name='songs')
    # ### end Alembic commands ###
