"""Add chart model

Revision ID: 10523eeaf3ff
Revises: 0ec3206ee2f8
Create Date: 2020-07-02 10:31:24.968748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10523eeaf3ff'
down_revision = '0ec3206ee2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('station', sa.String(length=250), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charts_artist_id'), 'charts', ['artist_id'], unique=False)
    op.create_index(op.f('ix_charts_song_id'), 'charts', ['song_id'], unique=False)
    op.create_index(op.f('ix_charts_station'), 'charts', ['station'], unique=False)
    op.create_index(op.f('ix_week_year'), 'charts', ['year', 'week'], unique=False)
    op.drop_table('played_old')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('played_old',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('played_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('song_slug', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='played_old_pkey')
    )
    op.drop_index('week_year', table_name='charts')
    op.drop_index(op.f('ix_charts_station'), table_name='charts')
    op.drop_index(op.f('ix_charts_song_id'), table_name='charts')
    op.drop_index(op.f('ix_charts_artist_id'), table_name='charts')
    op.drop_table('charts')
    # ### end Alembic commands ###
