"""Change played time column to use a timezone

Revision ID: 63ed5d88e84b
Revises: 7c2b39c913a5
Create Date: 2020-08-14 13:15:17.020465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ed5d88e84b'
down_revision = '7c2b39c913a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'played', 'songs', ['song_id'], ['id'])
    op.create_foreign_key(None, 'played', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'played', type_='foreignkey')
    op.drop_constraint(None, 'played', type_='foreignkey')
    # ### end Alembic commands ###
